#!/usr/bin/env python3
"""Run and preserve real-world validation evidence outside pytest.

Writes, per scenario: report.pdf (and report-v2.pdf where an asset freeze check ran), snapshot.json, result.json,
completeness.json and pages/page-NN.png; plus summary.json and assessment.md across scenarios. Narratives use the
deterministic mock provider, so no key, network or login is involved.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
BACKEND = REPO / "backend"
for candidate in (str(REPO), str(BACKEND)):
    if candidate not in sys.path:
        sys.path.insert(0, candidate)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario", action="append", default=[], help="scenario id to run; repeat to select several")
    parser.add_argument("--output", type=Path, default=HERE / "results", help="directory for preserved evidence")
    parser.add_argument("--timeout", type=float, default=240, help="seconds to wait for each background stage")
    return parser.parse_args()


def assessment_markdown(results: list[dict]) -> str:
    lines = ["# Real-world validation assessment (generated)", "", "Generated by `run_validation.py`. Complete means the completeness specification reported no gap before",
             "generation; structural means the package was ingested and rendered while the listed gaps stayed open by design.", ""]
    lines += ["| Scenario | Classification | Result | Gaps | Drafted | Files (processed / unrecognized / unsupported / needs OCR / failed) | Pages | Images p1, p2 |", "|---|---|---|---:|---:|---|---:|---|"]
    for r in results:
        fs = r.get("file_summary", {})
        rep = r.get("report", {})
        imgs = rep.get("images_per_page") or []
        lines.append(f"| {r['scenario']} | {r['classification']} | {'PASS' if r['passed'] else 'FAIL'} | {r.get('completeness', {}).get('gap_count', 'n/a')} | {len(r.get('drafted', []))} | "
                     f"{fs.get('processed', 0)} / {fs.get('unrecognized', 0)} / {fs.get('unsupported', 0)} / {fs.get('needs_ocr', 0)} / {fs.get('failed', 0)} | {rep.get('page_count', 'n/a')} | {imgs[:2] if imgs else 'n/a'} |")
    for r in results:
        lines += ["", f"## {r['scenario']} ({r['classification']})", ""]
        if r["failures"]:
            lines += ["Failures:", ""] + [f"- {f}" for f in r["failures"]] + [""]
        lines += ["Value provenance by page (fields and table cells in the version snapshot):", "",
                  "| Page | Extracted | Derived | Reviewer corrections | Mock drafts | Missing (intentional or optional) | Missing (unexpected) | Conflicts |", "|---:|---:|---:|---:|---:|---:|---:|---:|"]
        for page, c in (r.get("provenance") or {}).items():
            lines.append(f"| {page} | {c['extracted']} | {c['derived']} | {c['corrected']} | {c['drafted']} | {c['missing_intentional']} | {c['missing_unexpected']} | {c['conflict']} |")
        gaps = r.get("completeness", {}).get("gaps", [])
        if gaps:
            lines += ["", f"Open gaps ({len(gaps)}):", ""] + [f"- page {g['page']}: {g['label']} ({g['path']}), {g['reason']}" for g in gaps]
        if r.get("report", {}).get("page_images"):
            lines += ["", "Page images: " + ", ".join(Path(p).name for p in r["report"]["page_images"])]
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    os.environ["APP_DATA_DIR"] = tempfile.mkdtemp(prefix="irg-real-world-")
    os.environ["APP_WORKERS"] = "3"
    os.environ.pop("ANTHROPIC_API_KEY", None)
    os.environ["NARRATIVE_PROVIDER"] = "mock"

    from fastapi.testclient import TestClient

    from app.main import app
    from validation.real_world.harness import discover_scenarios, run_many

    scenarios = discover_scenarios()
    if args.scenario:
        requested = set(args.scenario)
        scenarios = [scenario for scenario in scenarios if scenario.scenario_id in requested]
        missing = requested - {scenario.scenario_id for scenario in scenarios}
        if missing:
            print(f"Unknown scenario(s): {', '.join(sorted(missing))}", file=sys.stderr)
            return 2
    args.output.mkdir(parents=True, exist_ok=True)
    with TestClient(app) as client:
        results = run_many(client, scenarios, args.output, timeout=args.timeout)

    summary = {
        "passed": all(result["passed"] for result in results),
        "scenario_count": len(results),
        "passed_count": sum(result["passed"] for result in results),
        "failed_count": sum(not result["passed"] for result in results),
        "scenarios": [
            {"id": r["scenario"], "classification": r["classification"], "passed": r["passed"], "failures": r["failures"],
             "complete": r.get("completeness", {}).get("complete"), "gap_count": r.get("completeness", {}).get("gap_count"),
             "drafted": len(r.get("drafted", [])), "stage_after_report": r.get("stage_after_report"), "report_page_count": r.get("report", {}).get("page_count")}
            for r in results
        ],
    }
    (args.output / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    (args.output / "assessment.md").write_text(assessment_markdown(results))
    for item in summary["scenarios"]:
        status = "PASS" if item["passed"] else "FAIL"
        print(f"{status} {item['id']} [{item['classification']}] gaps={item['gap_count']} drafted={item['drafted']}")
        for failure in item["failures"]:
            print(f"  - {failure}")
    print(f"{summary['passed_count']}/{summary['scenario_count']} scenarios passed; evidence: {args.output}")
    return 0 if summary["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
